{{- if .Values.volume.metricsPort }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "seaweedfs.name" . }}-volume1
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: volume1
spec:
  endpoints:
    - interval: 30s
      port: swfs-volume-metrics1
      scrapeTimeout: 5s
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: volume1
{{- end }}